// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NetworkingInfo.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkingInfo struct {
	Profile              *NetworkingInfo_Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Picture              string                  `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NetworkingInfo) Reset()         { *m = NetworkingInfo{} }
func (m *NetworkingInfo) String() string { return proto.CompactTextString(m) }
func (*NetworkingInfo) ProtoMessage()    {}
func (*NetworkingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c10dfdbd2a9b46d, []int{0}
}

func (m *NetworkingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkingInfo.Unmarshal(m, b)
}
func (m *NetworkingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkingInfo.Marshal(b, m, deterministic)
}
func (m *NetworkingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkingInfo.Merge(m, src)
}
func (m *NetworkingInfo) XXX_Size() int {
	return xxx_messageInfo_NetworkingInfo.Size(m)
}
func (m *NetworkingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkingInfo proto.InternalMessageInfo

func (m *NetworkingInfo) GetProfile() *NetworkingInfo_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *NetworkingInfo) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

type NetworkingInfo_Profile struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Biography            string   `protobuf:"bytes,5,opt,name=biography,proto3" json:"biography,omitempty"`
	FacebookUrl          string   `protobuf:"bytes,20,opt,name=facebook_url,json=facebookUrl,proto3" json:"facebook_url,omitempty"`
	TwitterUrl           string   `protobuf:"bytes,21,opt,name=twitter_url,json=twitterUrl,proto3" json:"twitter_url,omitempty"`
	LinkedinUrl          string   `protobuf:"bytes,22,opt,name=linkedin_url,json=linkedinUrl,proto3" json:"linkedin_url,omitempty"`
	WebsiteUrl           string   `protobuf:"bytes,23,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkingInfo_Profile) Reset()         { *m = NetworkingInfo_Profile{} }
func (m *NetworkingInfo_Profile) String() string { return proto.CompactTextString(m) }
func (*NetworkingInfo_Profile) ProtoMessage()    {}
func (*NetworkingInfo_Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c10dfdbd2a9b46d, []int{0, 0}
}

func (m *NetworkingInfo_Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkingInfo_Profile.Unmarshal(m, b)
}
func (m *NetworkingInfo_Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkingInfo_Profile.Marshal(b, m, deterministic)
}
func (m *NetworkingInfo_Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkingInfo_Profile.Merge(m, src)
}
func (m *NetworkingInfo_Profile) XXX_Size() int {
	return xxx_messageInfo_NetworkingInfo_Profile.Size(m)
}
func (m *NetworkingInfo_Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkingInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkingInfo_Profile proto.InternalMessageInfo

func (m *NetworkingInfo_Profile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetFacebookUrl() string {
	if m != nil {
		return m.FacebookUrl
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetTwitterUrl() string {
	if m != nil {
		return m.TwitterUrl
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetLinkedinUrl() string {
	if m != nil {
		return m.LinkedinUrl
	}
	return ""
}

func (m *NetworkingInfo_Profile) GetWebsiteUrl() string {
	if m != nil {
		return m.WebsiteUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*NetworkingInfo)(nil), "beilmo.spectre.dto.NetworkingInfo")
	proto.RegisterType((*NetworkingInfo_Profile)(nil), "beilmo.spectre.dto.NetworkingInfo.Profile")
}

func init() { proto.RegisterFile("NetworkingInfo.proto", fileDescriptor_6c10dfdbd2a9b46d) }

var fileDescriptor_6c10dfdbd2a9b46d = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4d, 0x6a, 0xe3, 0x40,
	0x10, 0x85, 0xc7, 0xf6, 0x78, 0x3c, 0x6a, 0x9b, 0x59, 0x34, 0x9e, 0x19, 0xe5, 0x8f, 0xd8, 0x59,
	0x99, 0x80, 0x25, 0x48, 0x36, 0x59, 0x87, 0x6c, 0xb2, 0x31, 0xc1, 0x60, 0x08, 0xd9, 0x18, 0x49,
	0x2e, 0xc9, 0x85, 0x5b, 0x5d, 0xa2, 0x55, 0xc2, 0xf8, 0x24, 0xb9, 0x40, 0x4e, 0x91, 0xd3, 0x05,
	0x75, 0x4b, 0x81, 0x38, 0xcb, 0xfa, 0xde, 0x57, 0xaf, 0x84, 0x68, 0x31, 0x5e, 0x00, 0xef, 0xc9,
	0xec, 0x50, 0x67, 0x8f, 0x3a, 0xa5, 0xa0, 0x30, 0xc4, 0x24, 0x65, 0x0c, 0xa8, 0x72, 0x0a, 0xca,
	0x02, 0x12, 0x36, 0x10, 0x6c, 0x98, 0xae, 0x5e, 0x7b, 0xe2, 0xcf, 0x57, 0x59, 0x3e, 0x88, 0x41,
	0x61, 0x28, 0x45, 0x05, 0x7e, 0x67, 0xd2, 0x99, 0x0d, 0x6f, 0xae, 0x83, 0xef, 0x8b, 0xc1, 0xd1,
	0x85, 0x27, 0xb7, 0xb1, 0x6c, 0x57, 0xa5, 0x2f, 0x06, 0x05, 0x26, 0x5c, 0x19, 0xf0, 0xbb, 0x93,
	0xce, 0xcc, 0x5b, 0xb6, 0xe3, 0xe9, 0x5b, 0x57, 0x0c, 0x1a, 0x5d, 0x5e, 0x08, 0x91, 0xa2, 0x29,
	0x79, 0xad, 0xa3, 0xdc, 0x9d, 0xf3, 0x96, 0x9e, 0x25, 0x8b, 0x28, 0x07, 0x79, 0x26, 0x3c, 0x15,
	0xb5, 0xa9, 0xab, 0xf9, 0x5d, 0x03, 0x1b, 0x8e, 0x45, 0x1f, 0xf2, 0x08, 0x95, 0xdf, 0xb3, 0x81,
	0x1b, 0xe4, 0x54, 0x8c, 0x8a, 0x2d, 0x69, 0x58, 0xeb, 0x2a, 0x8f, 0xc1, 0xf8, 0x3f, 0x6d, 0x38,
	0xb4, 0x6c, 0x61, 0x91, 0x3c, 0x17, 0x5e, 0x8c, 0x94, 0x99, 0xa8, 0xd8, 0x1e, 0xfc, 0xbe, 0xbb,
	0xf9, 0x09, 0xea, 0x82, 0x34, 0x4a, 0x20, 0x26, 0xda, 0xad, 0x2b, 0xa3, 0xfc, 0xb1, 0x2b, 0x68,
	0xd9, 0xca, 0x28, 0x79, 0x29, 0x86, 0xbc, 0x47, 0x66, 0x30, 0xd6, 0xf8, 0x6b, 0x0d, 0xd1, 0xa0,
	0x5a, 0x98, 0x8a, 0x91, 0x42, 0xbd, 0x83, 0x0d, 0x6a, 0x6b, 0xfc, 0x73, 0x1d, 0x2d, 0x6b, 0x3a,
	0xf6, 0x10, 0x97, 0xc8, 0x60, 0x8d, 0xff, 0xae, 0xa3, 0x41, 0x2b, 0xa3, 0xee, 0x9f, 0xc5, 0x49,
	0x42, 0xf9, 0xf1, 0xaf, 0x07, 0xcd, 0xc8, 0x87, 0x97, 0xbb, 0x0c, 0x79, 0x5b, 0xc5, 0x41, 0x42,
	0x79, 0xe8, 0x8c, 0xb0, 0x31, 0xe6, 0x19, 0xcd, 0x0d, 0x94, 0x3c, 0x8f, 0x0a, 0x0c, 0x51, 0x33,
	0x98, 0xfa, 0xcb, 0xcb, 0xb0, 0x1e, 0x37, 0x4c, 0xef, 0xdd, 0x1f, 0xf1, 0x2f, 0xfb, 0x1c, 0x6e,
	0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x9e, 0x2d, 0x64, 0x26, 0x02, 0x00, 0x00,
}
