// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Session.proto

package beilmo_spectre_entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Session struct {
	Id       int64  `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Abstract string `protobuf:"bytes,3,opt,name=abstract,proto3" json:"abstract,omitempty"`
	Room     string `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	// The number of seconds since midnight on January 1, 1970 in GMT. (UNIX epoch time)
	Date float64 `protobuf:"fixed64,5,opt,name=date,proto3" json:"date,omitempty"`
	// The time interval required for this session, measured in seconds.
	Duration             int32      `protobuf:"zigzag32,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Speakers             []*Speaker `protobuf:"bytes,7,rep,name=speakers,proto3" json:"speakers,omitempty"`
	Keywords             []string   `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_820f45a0f2bb7a38, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Session) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Session) GetAbstract() string {
	if m != nil {
		return m.Abstract
	}
	return ""
}

func (m *Session) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *Session) GetDate() float64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Session) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Session) GetSpeakers() []*Speaker {
	if m != nil {
		return m.Speakers
	}
	return nil
}

func (m *Session) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "beilmo.spectre.entity.Session")
}

func init() { proto.RegisterFile("Session.proto", fileDescriptor_820f45a0f2bb7a38) }

var fileDescriptor_820f45a0f2bb7a38 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0xd2, 0x9f, 0x60, 0x54, 0x24, 0x2c, 0x90, 0x4c, 0x17, 0x95, 0xc5, 0xca, 0x2b,
	0x2f, 0x60, 0xc7, 0x92, 0x23, 0xb8, 0x27, 0x70, 0xe2, 0x59, 0x58, 0x6d, 0x32, 0x91, 0x3d, 0x08,
	0xf5, 0x6a, 0x5c, 0x88, 0x6b, 0x20, 0x3b, 0x6d, 0x56, 0xd9, 0xcd, 0x37, 0x7e, 0x7e, 0x7a, 0x6f,
	0xf8, 0xee, 0x08, 0x29, 0x05, 0x1c, 0xcc, 0x18, 0x91, 0x50, 0xbc, 0xb4, 0x10, 0xce, 0x3d, 0x9a,
	0x34, 0x42, 0x47, 0x11, 0x0c, 0x0c, 0x14, 0xe8, 0xb2, 0xdf, 0x1d, 0x47, 0x70, 0x27, 0x88, 0x93,
	0xea, 0xed, 0x8f, 0xf1, 0xed, 0xf5, 0x9f, 0x78, 0xe4, 0x55, 0xf0, 0x92, 0x29, 0xa6, 0x85, 0xad,
	0x82, 0x17, 0xcf, 0x7c, 0x4d, 0x81, 0xce, 0x20, 0x2b, 0xc5, 0xf4, 0xbd, 0x9d, 0x40, 0xec, 0x79,
	0xe3, 0xda, 0x44, 0xd1, 0x75, 0x24, 0xeb, 0xf2, 0x30, 0xb3, 0x10, 0x7c, 0x15, 0x11, 0x7b, 0xb9,
	0x2a, 0xfb, 0x32, 0xe7, 0x9d, 0x77, 0x04, 0x72, 0xad, 0x98, 0x66, 0xb6, 0xcc, 0xd9, 0xc3, 0x7f,
	0x47, 0x47, 0x01, 0x07, 0xb9, 0x51, 0x4c, 0x3f, 0xd9, 0x99, 0xc5, 0x27, 0x6f, 0xd2, 0x14, 0x31,
	0xc9, 0xad, 0xaa, 0xf5, 0xc3, 0xfb, 0xc1, 0x2c, 0x56, 0x31, 0xd7, 0x26, 0x76, 0xd6, 0x67, 0xdf,
	0x13, 0x5c, 0x7e, 0x30, 0xfa, 0x24, 0x1b, 0x55, 0xe7, 0x6c, 0x37, 0xfe, 0x3a, 0xf0, 0xd7, 0x0e,
	0xfb, 0x65, 0xab, 0xdf, 0xea, 0xae, 0xdd, 0x94, 0x83, 0x7c, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xf1, 0x67, 0x7d, 0x90, 0x47, 0x01, 0x00, 0x00,
}
