// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Speaker.proto

package beilmo_spectre_entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Speaker struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	JobTitle             string   `protobuf:"bytes,4,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Company              string   `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	Biography            string   `protobuf:"bytes,6,opt,name=biography,proto3" json:"biography,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,7,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	FacebookUrl          string   `protobuf:"bytes,20,opt,name=facebook_url,json=facebookUrl,proto3" json:"facebook_url,omitempty"`
	TwitterUrl           string   `protobuf:"bytes,21,opt,name=twitter_url,json=twitterUrl,proto3" json:"twitter_url,omitempty"`
	LinkedinUrl          string   `protobuf:"bytes,22,opt,name=linkedin_url,json=linkedinUrl,proto3" json:"linkedin_url,omitempty"`
	WebsiteUrl           string   `protobuf:"bytes,23,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Speaker) Reset()         { *m = Speaker{} }
func (m *Speaker) String() string { return proto.CompactTextString(m) }
func (*Speaker) ProtoMessage()    {}
func (*Speaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7848ad4e5bc6b60, []int{0}
}

func (m *Speaker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Speaker.Unmarshal(m, b)
}
func (m *Speaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Speaker.Marshal(b, m, deterministic)
}
func (m *Speaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Speaker.Merge(m, src)
}
func (m *Speaker) XXX_Size() int {
	return xxx_messageInfo_Speaker.Size(m)
}
func (m *Speaker) XXX_DiscardUnknown() {
	xxx_messageInfo_Speaker.DiscardUnknown(m)
}

var xxx_messageInfo_Speaker proto.InternalMessageInfo

func (m *Speaker) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Speaker) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Speaker) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Speaker) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Speaker) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Speaker) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *Speaker) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *Speaker) GetFacebookUrl() string {
	if m != nil {
		return m.FacebookUrl
	}
	return ""
}

func (m *Speaker) GetTwitterUrl() string {
	if m != nil {
		return m.TwitterUrl
	}
	return ""
}

func (m *Speaker) GetLinkedinUrl() string {
	if m != nil {
		return m.LinkedinUrl
	}
	return ""
}

func (m *Speaker) GetWebsiteUrl() string {
	if m != nil {
		return m.WebsiteUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Speaker)(nil), "beilmo.spectre.entity.Speaker")
}

func init() { proto.RegisterFile("Speaker.proto", fileDescriptor_a7848ad4e5bc6b60) }

var fileDescriptor_a7848ad4e5bc6b60 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0x47, 0xbf, 0xe4, 0x83, 0x86, 0x4c, 0x81, 0x85, 0x45, 0xc1, 0x88, 0x7f, 0x85, 0x55, 0x57,
	0xd9, 0x70, 0x03, 0x0e, 0xc0, 0xa2, 0xd0, 0x75, 0x64, 0x27, 0x53, 0xea, 0xc6, 0xc9, 0x58, 0xce,
	0xa0, 0x2a, 0x57, 0xe3, 0x12, 0x5c, 0x09, 0xc5, 0x49, 0x58, 0xb1, 0x9c, 0xf7, 0x7e, 0x7a, 0x91,
	0x62, 0x38, 0x7b, 0x73, 0xa8, 0x2a, 0xf4, 0x99, 0xf3, 0xc4, 0x24, 0x16, 0x1a, 0x8d, 0xad, 0x29,
	0x6b, 0x1d, 0x16, 0xec, 0x31, 0xc3, 0x86, 0x0d, 0x77, 0x4f, 0xdf, 0x31, 0x24, 0xe3, 0x50, 0x9c,
	0x43, 0x6c, 0x4a, 0x19, 0x2d, 0xa3, 0x95, 0x58, 0xc7, 0xa6, 0x14, 0x77, 0x00, 0x5b, 0xe3, 0x5b,
	0xce, 0x1b, 0x55, 0xa3, 0x8c, 0x97, 0xd1, 0x2a, 0x5d, 0xa7, 0x81, 0xbc, 0xaa, 0x1a, 0xc5, 0x0d,
	0xa4, 0x56, 0x4d, 0xf6, 0x7f, 0xb0, 0x27, 0x3d, 0x98, 0xe4, 0x9e, 0x74, 0xce, 0x86, 0x2d, 0xca,
	0xa3, 0x41, 0xee, 0x49, 0xbf, 0xf7, 0xb7, 0x90, 0x90, 0x14, 0x54, 0x3b, 0xd5, 0x74, 0xf2, 0x38,
	0xa8, 0xe9, 0x14, 0xb7, 0x90, 0x6a, 0x43, 0x1f, 0x5e, 0xb9, 0x5d, 0x27, 0x67, 0xc3, 0x17, 0x7f,
	0x41, 0x1f, 0x75, 0x3b, 0x62, 0xca, 0x3f, 0xbd, 0x95, 0xc9, 0x10, 0x0d, 0x60, 0xe3, 0xad, 0x78,
	0x84, 0xd3, 0xad, 0x2a, 0x50, 0x13, 0x55, 0xc1, 0x5f, 0x04, 0x3f, 0x9f, 0x58, 0x3f, 0x79, 0x80,
	0x39, 0x1f, 0x0c, 0x33, 0xfa, 0xb0, 0x58, 0x84, 0x05, 0x8c, 0x68, 0x6c, 0x58, 0xd3, 0x54, 0x58,
	0x9a, 0x26, 0x2c, 0x2e, 0x87, 0xc6, 0xc4, 0xc6, 0xc6, 0x01, 0x75, 0x6b, 0x18, 0xc3, 0xe2, 0x6a,
	0x68, 0x8c, 0x68, 0xe3, 0xed, 0xcb, 0x3d, 0x5c, 0x17, 0x54, 0x67, 0x7f, 0xfe, 0xee, 0xaf, 0xf8,
	0x9f, 0x9e, 0x85, 0xf7, 0x78, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xa6, 0xbd, 0x23, 0xa0,
	0x01, 0x00, 0x00,
}
